Repository sampadatiwari30/Code_Creations, pull requests merged in 2025-09, with the labels that each got.

#24 Enhance Project Page with Modern UI/UX and Interactive Cards
  expierence.html
  images/contract-project.jpeg
  images/defi-platform-project.jpeg
  images/desh-darshan.png
  images/hearme-project.jpeg
  images/kala.ficial.png
  images/nasa-space_project.jpeg
  images/spam-mail-project.png
  index.html
  project.html
Labels: enhancement, gssoc25

#34 Fixed:Enhancement of 'Get in Touch' Section
  contact.html
Labels: enhancement, gssoc25

#50 Issue #44 fixed
  index.html
  project.html
Labels: enhancement, gssoc25

#65 fix: PWA manifest and service worker setup
  index.html
  manifest.json
  offline.html
  sw.js
Labels: documentation, gssoc25

#68 fix:Duplicate nav links in Navbar
  index.html
Labels: bug, gssoc25

#61 Fix/nav links skills
  index.html
Labels: bug, gssoc25

#87 Fix: Updated home link in all #73, #74, #75, #76, #77
  experience.html
  index.html
  project.html
  skills.html
Labels: bug, gssoc25

#90 Redesign contact page
  contact.html
Labels: enhancement, gssoc25

#94 Enhance UI of About Us Page
  .vscode/settings.json
  about.html
  css/about.css
Labels: enhancement, gssoc25

#96 fix:Added Navbar in Contact Section similar to other pages
  contact.html
Labels: enhancement, gssoc25

#97 🎯 Enhancement Request: Improve UI/UX of "Contact Me" Section in index.html + background (#88)
  css/index.css
  index.html
Labels: enhancement, gssoc25
