Repository sampadatiwari30/Code_Creations, pull requests merged in 2025-10, with the labels that each got.

#106 fixed code consistency and applied linting
  .eslintrc.json
  .prettierrc
  .vscode/settings.json
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
  about.html
  contact.html
  css/about.css
  css/contact.css
  css/experience.css
  css/index.css
  css/project.css
  css/skills.css
  experience.html
  index.html
  js/about.js
  js/contact.js
  js/experience.js
  js/index.js
  js/project.js
  js/skills.js
  offline.html
  project.html
  skills.html
  sw.js
Labels: documentation, gssoc25

#110 Add scroll top/bottom arrow button functionality
  project.html
Labels: bug, gssoc25

#120 Add Certificates / Achievements Page
  about.html
  achievements.html
  contact.html
  experience.html
  project.html
Labels: enhancement, gssoc25

#122 fix: Hamburger menu text not visible in mobile view
  index.html
Labels: bug, gssoc25
